{{- define "myapp.secret-dev" -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secret.name }}
  namespace: {{ .Release.Namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "0"
type: Opaque
data:
  username: {{ "dev_user" | b64enc }}
  password: {{ "dev_pass@123" | b64enc }}
{{- end }}
