{{- if eq .Values.secret.env "dev" }}
{{- include (print $.Template.BasePath "/secrets/secret-dev.yaml") . }}
{{- else }}
{{- fail (printf "Invalid environment: %s. Must be one of dev/uat/prod" .Values.secret.env) }}
{{- end }}

