apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secret.name }}
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  username: {{ "dev_user" | b64enc }}
  password: {{ "dev_pass@123" | b64enc }}
  db_host:  {{ "dev-db.internal.local" | b64enc }}



