replicaCount: 3

image:
  repository: nginx
  tag: "latest"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80

config:
  message: "Welcome to Helm + Argo CD Demo"

secret:
  name: myapp-secret
  env: dev    # dev | uat | prod

