apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: helm-app
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/avadhutpatil22/How-deploy-your-application-using-Argo-CD-on-AKS-2026
    targetRevision: main
    path: values.yaml

  destination:
    server: https://kubernetes.default.svc
    namespace: default

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
